### ISSUE TITLE
Exercise #10 Array Methods confusing test

### ISSUE THREAD

**Issue by AbreuY** [4GeeksAcademy/javascript-functions-exercises-tutorial#36]
The test evaluates that the function returns two different arrays. Shouldn't it be one? This is somewhat confusing because the test fails. 
In addition, an unnecessary parameter is being passed to the sortNames function, since it does not receive parameters.

**Comment by tommygonzaleza** [comment]
This issue has been fixed already. Here is the solution: https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/commit/7ecdeaf0117f3d58c93d73edf2838f2db2ba97d3
